// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrchppqshsqfvwqofves.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yY2hwcHFzaHNxZnZ3cW9mdmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzU0MzUsImV4cCI6MjA2NTY1MTQzNX0.axl5f7QZEo4VpTkTXbynugTB38tsi33PWT0AvZjkf00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);